#!/bin/bash

# system - Ascript to produce an HTML file with system info

cat << _EOF_
<html>
<head>
    <title>
    The title
    <title>
<head>

<body>
    Page content will be here.
<body>
</html>
_EOF_
